name: New Translation Community Request
description: Request to establish a translation community for a new language of the Open Guide to Kanban
title: "🌐 [LANGUAGE_CODE] LANGUAGE_NAME Translation Community"
labels: ["translation", "community", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in establishing a translation community for the Open Guide to Kanban! 

        Translations are community-owned efforts that bring together multiple contributors including translators, reviewers, and community members. This form helps us establish a collaborative translation community for your target language.

        **Community Approach:** The community owns the translations, not individuals or groups. Multiple people can contribute, take over, or maintain translations over time, creating a sustainable and collaborative effort.

        **Title Format:** When creating this issue, please update the title to format: `🌐 [LANGUAGE_CODE] Language Name Translation Community`
        - Examples: `🌐 [pl] Polish Translation Community`, `🌐 [es-419] Español Latino Translation Community`

        **Before submitting:** Please check existing issues and discussions to ensure this language community is not already being established. We encourage joining existing efforts rather than creating competing translations.
  - type: checkboxes
    id: language-check
    attributes:
      label: Pre-submission Check
      description: Please confirm the following before proceeding
      options:
        - label: I have checked that this language community has not already been established or is currently being organized
          required: true
  - type: input
    id: language
    attributes:
      label: Target Language
      description: What language would you like to establish a translation community for?
      placeholder: e.g., Portuguese, Italian, Japanese
    validations:
      required: true
  - type: input
    id: language-code
    attributes:
      label: Language Code
      description: |
        ISO 639-1 language code for this language. This will be used in the issue title format.

        **Examples:**
        - `pl` for Polish → `🌐 [pl] Polish Translation Community`
        - `es` for Spanish → `🌐 [es] Spanish Translation Community`
        - Combined with region: `es-419` → `🌐 [es-419] Español Latino Translation Community`
      placeholder: e.g., pt, it, ja, en, es, pl
    validations:
      required: true

  - type: input
    id: country-code
    attributes:
      label: Region/Country Code (Optional)
      description: |
        ISO 3166-1 alpha-2 country code OR UN M.49 region code for regional/cultural variations:

        **Country Examples:**
        - pt-BR (Brazilian Portuguese), en-GB (British English), es-MX (Mexican Spanish)

        **Region Examples:**
        - es-419 (Latin American Spanish - covers Latin America & Caribbean region)

        **Format:** Use country codes (BR, GB, MX) or region codes (419) as appropriate for your target community.
      placeholder: e.g., BR, GB, MX, 419
  - type: input
    id: community-organizer
    attributes:
      label: Community Organizer/Coordinator
      description: Who is coordinating this translation community? (This information helps us communicate with the community)
      placeholder: e.g., John Doe, Kanban Community Portugal, or Regional Kanban Group
    validations:
      required: true
  - type: input
    id: community-contact
    attributes:
      label: Community Contact Information (Optional)
      description: Link to community website, LinkedIn profile, or organization page that can serve as a contact point
      placeholder: e.g., https://kanbancommunityportugal.org or https://www.linkedin.com/in/johndoe
  - type: dropdown
    id: community-readiness
    attributes:
      label: Community Translation Readiness
      description: What translation resources does your community have available?
      options:
        - We have professional translators ready to contribute
        - We have native speakers with translation experience
        - We have native speakers willing to learn translation processes
        - We are organizing and building our translation team
        - Other (please specify in additional info)
    validations:
      required: true
  - type: dropdown
    id: community-kanban-experience
    attributes:
      label: Community Kanban Experience
      description: What is the Kanban experience level in your translation community?
      options:
        - We have certified Kanban practitioners (TKP/KMP/KCF)
        - We have experienced Kanban practitioners (2+ years)
        - We have some Kanban experience in the community
        - We are new to Kanban but eager to learn and contribute
        - Mixed experience levels across the community
    validations:
      required: true
  - type: textarea
    id: community-motivation
    attributes:
      label: Community Impact and Motivation
      description: Why does your community need this translation? How will it help your local Kanban practitioners and organizations?
      placeholder: Tell us about the community need, expected impact, and how this translation will serve your local Kanban ecosystem...
    validations:
      required: true

  - type: textarea
    id: community-capacity
    attributes:
      label: Community Capacity and Timeline
      description: |
        How many reviewers can your community provide? (Minimum 5 required by our Code of Conduct)
        What is your estimated timeline for completing the translation?
        Who are the potential contributors in your community?
      placeholder: |
        Reviewers: We can provide X reviewers (Y with Kanban knowledge, Z without)
        Timeline: X weeks/months
        Contributors: Brief description of your translation community team...
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any other information you'd like to share about this translation community establishment?
      placeholder: Include any relevant details about your community, existing translation initiatives, or special considerations...
  - type: checkboxes
    id: terms
    attributes:
      label: Community Agreement
      description: By submitting this request, the translation community agrees to the following terms
      options:
        - label: Our community has read and agrees to the [Translation Guide](https://github.com/KanbanGuides/KanbanGuides/blob/main/docs/translations.md)
          required: true
        - label: Our community has read and agrees to the [Code of Conduct for Translators](https://github.com/KanbanGuides/KanbanGuides/blob/main/docs/translations-code-of-conduct.md)
          required: true
        - label: Our community has read and agrees to the [Community Code of Conduct](https://github.com/KanbanGuides/KanbanGuides/blob/main/CODE_OF_CONDUCT.md)
          required: true
        - label: We understand that the community owns the translation, not individuals or groups, and that others may contribute or take over maintenance over time
          required: true

  - type: markdown
    attributes:
      value: |
        ---        **Next Steps:**
        1. A project maintainer will review your community translation request
        2. If approved, your translation community will receive access to resources and guidelines
        3. We'll help establish the community coordination process and connect you with other contributors
        4. Your community will work together to complete the translation with the required minimum of 5 reviewers
        5. Upon completion, the translation will be published and the community will be credited

        Thank you for building the global Kanban community! 🌐🎉
